### PR TITLE
Admin Dashboard - User Stories 19 & 20

### PR DESCRIPTION
**Pull request by hamouj**
User Story 19
 Routes: Create admin index route (dashboard)
 View: Create admin index view
 Controller: Create controller index action
 Spec: Create feature test for admin index

User Story 20
 Routes: Create admin invoices index route
 View: Add links to admin index view
 Spec: Add test for presence and functionality of links

### CODE REVIEW

**Review by axeldelaguardia — COMMENTED** [review]
Changes look good! Thanks for adding all the relationship tests.

**Comment by Bphayes1200** [comment]
Thank you for the relationships!

**Review by MATrevino — COMMENTED** [review]
Nice work here

**Review by Bphayes1200 — COMMENTED** [review]
Looks Good!

**Pull request merged**
