### PR TITLE
User Story 36 Functionality and Tests

### PR DESCRIPTION
**Pull request by hamouj**
This PR will:
-Update the invoice status in the admin/invoice show view to be a select field with the current status as the default selected
-Write tests for update to select field for invoice status
-Add the update action in the admin/invoices controller
-Add the PATCH method in the routes

### CODE REVIEW

**Review by axeldelaguardia — COMMENTED** [review]
Really like the use of the tables!!!

**Comment by Bphayes1200** [comment]
Great!

**Review by Bphayes1200 — APPROVED** [review]
Great

**Review by MATrevino — APPROVED** [review]
Great organization. Thanks, Jasmine!

**Pull request merged**
